name: Build ISO Image

on:
  push:
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker image
      run: |
        docker build -t archiso-builder -f build/Dockerfile .

    - name: Run archiso builder
      run: |
        mkdir -p out
        docker run --rm --privileged -v $PWD/out:/lingmo-archiso-build/out archiso-builder

    - name: Upload ISO
      uses: actions/upload-artifact@v4
      with:
        name: archiso
        path: ./out
