name: Build ISO Image

on:
  push:
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Pull Docker image
      run: docker pull archlinux

    - name: Cache pacman packages
      id: cache-pacman
      uses: actions/cache@v4
      with:
        path: /var/cache/pacman/pkg
        key: pacman
        restore-keys: |
          pacman

    - name: Run archiso builder
      run: |
        docker run --rm --privileged -v $PWD:/out -v pkg:/var/cache/pacman/pkg archlinux sh -c "
          pacman-key --init
          pacman -Syu --noconfirm archiso git memtest86+-efi memtest86+
          git clone --depth 1 https://github.com/LingmoOS/archlingmo-archiso-config /config
          mkarchiso -v /config/profile -o /out
        "

    - name: Upload ISO
      uses: actions/upload-artifact@v4
      with:
        name: archiso
        compression-level: 0
        path: ./*.iso
