name: Build ISO Image

on:
  push:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache pacman packages
      id: cache-pacman
      uses: actions/cache@v4
      with:
        path: pkg
        key: ${{ runner.os }}-pacman-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-pacman-

    - name: Pull Docker image
      run: |
        docker pull archlinux
      
    - name: Run archiso builder
      run: |
        docker run --rm --privileged -v $PWD:/out -v $PWD/pkg:/var/cache/pacman/pkg archlinux sh -c "
          pacman-key --init
          pacman-key --populate archlinux
          pacman -Syu --noconfirm archiso git memtest86+-efi memtest86+
          git clone --depth 1 https://github.com/LingmoOS/archlingmo-archiso-config /config
          pacman-key --lsign-key 'farseerfc@archlinux.org'
          pacman --config /config/profile/pacman.conf -Sy archlinuxcn-keyring
          mkarchiso -v /config/profile -o /out
        "

    - name: List contents in ISO
      run: 7z l *.iso

    - name: Upload ISO
      uses: actions/upload-artifact@v4
      with:
        name: archiso
        compression-level: 0
        path: ./*.iso
