name: Build ISO Image

on:
  push:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache Docker image
      id: cache-docker-image
      uses: actions/cache@v4
      with:
        path: builder.tar.zst
        key: ${{ runner.os }}-docker-image-${{ github.sha }}
        restore-keys: ${{ runner.os }}-docker-image-

    - name: test
      if: steps.cache-docker-image.outputs.cache-hit == 'true'
      run: echo test

    - name: Load Docker image from cache
      if: steps.cache-docker-image.outputs.cache-hit != 'true'
      run: zstd -d builder.tar.zst -o - | docker load
    
    - name: Build Docker image
      if: steps.cache-docker-image.outputs.cache-hit != 'true'
      run: |
        docker build -t builder https://github.com/LingmoOS/archlingmo-archiso-config.git
        docker save builder | zstd -o builder.tar.zst

    - name: Run archiso builder
      run: docker run --rm --privileged -v $PWD/out:/out -v $PWD/pkg:/var/cache/pacman/pkg builder

    - name: List contents in ISO
      run: 7z l out/*.iso

    - name: Upload ISO
      uses: actions/upload-artifact@v4
      with:
        name: archiso
        compression-level: 0
        path: out/*.iso
