name: Build ISO Image

on:
  push:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: ${{ runner.os }}-buildx-

    - name: Build Docker image
      run: |
        docker buildx --cache-from=type=local,src=/tmp/.buildx-cache \
                     --cache-to=type=local,dest=/tmp/.buildx-cache-new \
                     -t builder https://github.com/LingmoOS/archlingmo-archiso-config.git

    - name: Cache pacman packages
      id: cache-pacman
      uses: actions/cache@v4
      with:
        path: pkg
        key: ${{ runner.os }}-pacman-${{ github.sha }}
        restore-keys: ${{ runner.os }}-pacman-
    
    - name: Run archiso builder
      run: docker run --rm --privileged -v $PWD/out:/out -v $PWD/pkg:/var/cache/pacman/pkg builder

    - name: List contents in ISO
      run: 7z l out/*.iso

    - name: Upload ISO
      uses: actions/upload-artifact@v4
      with:
        name: archiso
        compression-level: 0
        path: out/*.iso
